#!/bin/sh

#PBS -N trim-galore
#PBS -l nodes=1:ppn=16
#PBS -l walltime=24:00:00
#PBS -q longjob


starttime=$(date +"%s")
echo $(date -u -d @${starttime})
echo "options: time=24:00:00 n=1 ppn=1 q=longjob"
echo "$0"

# Set your working directory below.
#cd ../../project/waterland/<YOUR_ROOT_FOLDER>

for i in 1 2 3 4 5 6 7 8 9
do
    trim_galore --paired --trim1 --basename SRR7714${i} --output_dir Trimmed  SRR77140$i_1.fastq SRR77140$i_2.fastq
done

for i in 10 11 12
do
    trim_galore --paired --trim1 --basename SRR7714${i} --output_dir Trimmed  SRR7714${i}_1.fastq SRR7714${i}_2.fastq
done


endtime=$(date +"%s")
echo $(date -u -d @${endtime})
echo "Time elapsed" $(date -u -d @$(($endtime-$starttime)) +"%T")

